<#
.SYNOPSIS
    Validate and test package manager files generated by NekoRelease.

.DESCRIPTION
    This script validates the structure and format of package manager files,
    and optionally tests local installation for supported package managers.

.PARAMETER PackagePath
    Path to the packages directory (default: .\packages)

.PARAMETER PackageManagers
    Package managers to validate/test. If not specified, auto-detect from PackagePath.
    Valid values: Chocolatey, Scoop, Winget, vcpkg, Conan, Meson, Buckaroo, CPM

.PARAMETER ValidateOnly
    Only validate files without testing installation

.PARAMETER Verbose
    Show detailed validation information

.EXAMPLE
    .\Test-NekoPackages.ps1
    Auto-detect and validate all packages in .\packages

.EXAMPLE
    .\Test-NekoPackages.ps1 -PackageManagers @("vcpkg", "Conan") -Verbose
    Validate and test vcpkg and Conan packages with detailed output

.EXAMPLE
    .\Test-NekoPackages.ps1 -ValidateOnly
    Only validate package files without testing installation
#>

[CmdletBinding()]
param(
    [Parameter()]
    [string]$PackagePath = ".\packages",

    [Parameter()]
    [ValidateSet("Chocolatey", "Scoop", "Winget", "vcpkg", "Conan", "Meson", "Buckaroo", "CPM")]
    [string[]]$PackageManagers = @(),

    [Parameter()]
    [switch]$ValidateOnly
)

#region Helper Functions

function Write-Success {
    param([string]$Message)
    Write-Host "[OK] $Message" -ForegroundColor Green
}

function Write-Failure {
    param([string]$Message)
    Write-Host "[FAIL] $Message" -ForegroundColor Red
}

function Write-Warning {
    param([string]$Message)
    Write-Host "[WARN] $Message" -ForegroundColor Yellow
}

function Write-Info {
    param([string]$Message)
    Write-Host "[INFO] $Message" -ForegroundColor Cyan
}

function Write-SectionHeader {
    param([string]$Message)
    Write-Host "`n=====================================" -ForegroundColor Cyan
    Write-Host "  $Message" -ForegroundColor Cyan
    Write-Host "=====================================`n" -ForegroundColor Cyan
}

#endregion

#region Validation Functions

function Test-VcpkgPackage {
    param([string]$Path)
    
    Write-SectionHeader "Validating vcpkg Package"
    
    $issues = @()
    
    # Find the actual port directory (could be directly in Path or one level down)
    $portDir = $null
    if (Test-Path (Join-Path $Path "portfile.cmake")) {
        # Port files are directly in the provided path
        $portDir = Get-Item $Path
    } else {
        # Look for subdirectory containing port files
        $portDir = Get-ChildItem -Path $Path -Directory | Where-Object {
            Test-Path (Join-Path $_.FullName "portfile.cmake")
        } | Select-Object -First 1
    }
    
    if (-not $portDir) {
        $issues += "No port directory found with portfile.cmake"
        return @{
            Valid = $false
            Issues = $issues
            CanTest = $false
        }
    }
    
    Write-Info "Found port directory: $($portDir.Name)"
    
    $portfilePath = Join-Path $portDir.FullName "portfile.cmake"
    $vcpkgJsonPath = Join-Path $portDir.FullName "vcpkg.json"
    
    # Check portfile.cmake
    if (-not (Test-Path $portfilePath)) {
        $issues += "Missing portfile.cmake"
    } else {
        Write-Success "Found portfile.cmake"
        
        $portfile = Get-Content $portfilePath -Raw
        
        # Check for required vcpkg functions
        if ($portfile -notmatch "vcpkg_from_github") {
            $issues += "portfile.cmake missing vcpkg_from_github"
        } else {
            Write-Verbose "Found vcpkg_from_github"
        }
        
        if ($portfile -notmatch "(vcpkg_configure_cmake|vcpkg_cmake_configure)") {
            Write-Warning "portfile.cmake may be missing cmake configure command"
        }
        
        # Check for SHA512
        if ($portfile -notmatch "SHA512\s+[a-f0-9]{128}") {
            Write-Warning "portfile.cmake may be missing valid SHA512 hash"
        } else {
            Write-Success "Found SHA512 hash"
        }
    }
    
    # Check vcpkg.json
    if (-not (Test-Path $vcpkgJsonPath)) {
        $issues += "Missing vcpkg.json"
    } else {
        Write-Success "Found vcpkg.json"
        
        try {
            $vcpkgJson = Get-Content $vcpkgJsonPath -Raw | ConvertFrom-Json
            
            # Check required fields
            if (-not $vcpkgJson.name) { $issues += "vcpkg.json missing 'name'" }
            if (-not $vcpkgJson.version) { $issues += "vcpkg.json missing 'version'" }
            
            Write-Success "vcpkg.json is valid JSON"
            Write-Verbose "Port name: $($vcpkgJson.name)"
            Write-Verbose "Port version: $($vcpkgJson.version)"
        } catch {
            $issues += "Invalid JSON in vcpkg.json: $($_.Exception.Message)"
        }
    }
    
    return @{
        Valid = ($issues.Count -eq 0)
        Issues = $issues
        CanTest = $true
        PortPath = $portDir.Parent.FullName  # Parent directory for overlay-ports
        PortName = $portDir.Name
    }
}

function Test-ConanPackage {
    param([string]$Path)
    
    Write-SectionHeader "Validating Conan Package"
    
    $conanfile = Join-Path $Path "conanfile.py"
    $conandata = Join-Path $Path "conandata.yml"
    
    $issues = @()
    
    # Check conanfile.py
    if (-not (Test-Path $conanfile)) {
        $issues += "Missing conanfile.py"
    } else {
        Write-Success "Found conanfile.py"
        
        $content = Get-Content $conanfile -Raw
        
        # Check required class
        if ($content -notmatch "class\s+\w+\s*\(\s*ConanFile\s*\)") {
            $issues += "conanfile.py missing ConanFile class"
        } else {
            Write-Success "Found ConanFile class"
        }
        
        # Check required attributes
        $requiredAttrs = @("name", "version", "license", "url")
        foreach ($attr in $requiredAttrs) {
            if ($content -notmatch "$attr\s*=") {
                $issues += "conanfile.py missing attribute: $attr"
            } else {
                Write-Verbose "Found attribute: $attr"
            }
        }
        
        # Check for key methods
        if ($content -match "def source\(") {
            Write-Success "Found source method"
        }
        if ($content -match "def build\(") {
            Write-Success "Found build method"
        }
        if ($content -match "def package\(") {
            Write-Success "Found package method"
        }
    }
    
    # Check conandata.yml
    if (-not (Test-Path $conandata)) {
        Write-Warning "Missing conandata.yml (optional but recommended)"
    } else {
        Write-Success "Found conandata.yml"
        
        $content = Get-Content $conandata -Raw
        if ($content -match "sha256:") {
            Write-Success "Found SHA256 hash in conandata.yml"
        }
    }
    
    return @{
        Valid = ($issues.Count -eq 0)
        Issues = $issues
        CanTest = $true
        ConanfilePath = $conanfile
    }
}

#endregion

#region Test Installation Functions

function Test-VcpkgInstallation {
    param([string]$PortPath, [string]$PortName)
    
    Write-SectionHeader "Testing vcpkg Installation"
    
    # Check if vcpkg is installed
    if (-not (Get-Command vcpkg -ErrorAction SilentlyContinue)) {
        Write-Failure "vcpkg is not installed or not in PATH"
        Write-Info "Install vcpkg: https://vcpkg.io/"
        return $false
    }
    
    Write-Info "Testing port with vcpkg..."
    
    try {
        # Use overlay-ports to test local port
        Write-Info "Validating port: $PortName using overlay-ports..."
        Write-Info "Port path: $PortPath"
        
        $output = & vcpkg install $PortName --overlay-ports="$PortPath" --dry-run 2>&1 | Out-String
        
        if ($LASTEXITCODE -eq 0 -or $output -match "would be installed|The following packages will be") {
            Write-Success "Port structure validated by vcpkg"
            return $true
        } else {
            Write-Failure "vcpkg validation failed"
            Write-Host $output
            return $false
        }
    } catch {
        Write-Failure "vcpkg test failed: $($_.Exception.Message)"
        return $false
    }
}

function Test-ConanInstallation {
    param([string]$ConanfilePath)
    
    Write-SectionHeader "Testing Conan Recipe"
    
    # Check if Conan is installed
    if (-not (Get-Command conan -ErrorAction SilentlyContinue)) {
        Write-Failure "Conan is not installed or not in PATH"
        Write-Info "Install Conan: pip install conan"
        return $false
    }
    
    Write-Info "Testing Conan recipe..."
    
    try {
        $conanDir = Split-Path $ConanfilePath -Parent
        
        # Test recipe export (won't actually build, just validate)
        Write-Info "Validating recipe with 'conan export'..."
        $output = & conan export $conanDir 2>&1 | Out-String
        
        if ($LASTEXITCODE -eq 0) {
            Write-Success "Conan recipe validated successfully"
            return $true
        } else {
            Write-Failure "Conan validation failed"
            Write-Host $output
            return $false
        }
    } catch {
        Write-Failure "Conan test failed: $($_.Exception.Message)"
        return $false
    }
}

#endregion

#region Main Logic

function Get-AvailablePackageManagers {
    param([string]$BasePath)
    
    $available = @()
    
    if (Test-Path $BasePath) {
        $subdirs = Get-ChildItem -Path $BasePath -Directory
        
        foreach ($dir in $subdirs) {
            $name = $dir.Name
            
            # Normalize name
            if ($name -match "choco") { $available += "Chocolatey" }
            elseif ($name -match "scoop") { $available += "Scoop" }
            elseif ($name -match "winget") { $available += "Winget" }
            elseif ($name -match "vcpkg") { $available += "vcpkg" }
            elseif ($name -match "conan") { $available += "Conan" }
            elseif ($name -match "meson") { $available += "Meson" }
            elseif ($name -match "buckaroo") { $available += "Buckaroo" }
            elseif ($name -match "cpm") { $available += "CPM" }
        }
    }
    
    return $available | Select-Object -Unique
}

function Invoke-PackageValidation {
    param(
        [string]$PackageManager,
        [string]$Path
    )
    
    $result = switch ($PackageManager) {
        "vcpkg" { Test-VcpkgPackage -Path $Path }
        "Conan" { Test-ConanPackage -Path $Path }
        default { 
            Write-Warning "Validation for $PackageManager not yet implemented"
            return @{
                Valid = $null
                Issues = @()
                CanTest = $false
            }
        }
    }
    
    return $result
}

function Invoke-PackageTest {
    param(
        [string]$PackageManager,
        [hashtable]$ValidationResult
    )
    
    if (-not $ValidationResult.CanTest) {
        Write-Info "$PackageManager does not support local testing in this version"
        return $null
    }
    
    $result = switch ($PackageManager) {
        "vcpkg" { Test-VcpkgInstallation -PortPath $ValidationResult.PortPath -PortName $ValidationResult.PortName }
        "Conan" { Test-ConanInstallation -ConanfilePath $ValidationResult.ConanfilePath }
        default { $null }
    }
    
    return $result
}

#endregion

#region Entry Point

function Main {
    Write-Host "`n================================================" -ForegroundColor Cyan
    Write-Host "  NekoRelease Package Validation & Testing" -ForegroundColor Cyan
    Write-Host "================================================`n" -ForegroundColor Cyan
    
    # Validate PackagePath
    if (-not (Test-Path $PackagePath)) {
        Write-Failure "Package path not found: $PackagePath"
        Write-Info "Please ensure you've run NekoRelease.ps1 first to generate packages"
        exit 1
    }
    
    Write-Success "Package path: $PackagePath"
    
    # Auto-detect package managers if not specified
    if ($PackageManagers.Count -eq 0) {
        $PackageManagers = Get-AvailablePackageManagers -BasePath $PackagePath
        
        if ($PackageManagers.Count -eq 0) {
            Write-Failure "No package managers detected in $PackagePath"
            Write-Info "Directory structure:"
            Get-ChildItem -Path $PackagePath -Directory | ForEach-Object { Write-Host "  - $($_.Name)" }
            exit 1
        }
        
        Write-Info "Auto-detected package managers: $($PackageManagers -join ', ')"
    }
    
    # Results summary
    $results = @{}
    
    # Process each package manager
    foreach ($pm in $PackageManagers) {
        # Find package directory (case-insensitive match)
        $pmPath = Get-ChildItem -Path $PackagePath -Directory | Where-Object { 
            $_.Name -imatch "^$pm$" 
        } | Select-Object -First 1
        
        if (-not $pmPath) {
            Write-Warning "Could not find directory for $pm in $PackagePath"
            continue
        }
        
        $pmFullPath = $pmPath.FullName
        Write-Info "Processing $pm at: $pmFullPath"
        
        # Validation
        $validationResult = Invoke-PackageValidation -PackageManager $pm -Path $pmFullPath
        
        if ($validationResult -and $null -ne $validationResult.Valid) {
            if ($validationResult.Valid) {
                Write-Success "$pm package validation passed"
            } else {
                Write-Failure "$pm package validation failed:"
                foreach ($issue in $validationResult.Issues) {
                    Write-Host "    * $issue" -ForegroundColor Red
                }
            }
        }
        
        # Testing
        $testResult = $null
        if (-not $ValidateOnly -and $validationResult) {
            if ($validationResult.CanTest) {
                Write-Info "Testing $pm installation..."
                $testResult = Invoke-PackageTest -PackageManager $pm -ValidationResult $validationResult
            }
        }
        
        $results[$pm] = @{
            Validation = $validationResult
            Test = $testResult
        }
    }
    
    # Print summary
    Write-SectionHeader "Summary"
    
    $totalPassed = 0
    $totalFailed = 0
    $totalTested = 0
    
    foreach ($pm in $results.Keys) {
        $result = $results[$pm]
        
        Write-Host ("`n" + $pm + ":") -ForegroundColor Cyan
        
        if ($result.Validation -and $null -ne $result.Validation.Valid) {
            if ($result.Validation.Valid) {
                Write-Success "  Validation: PASSED"
                $totalPassed++
            } else {
                Write-Failure "  Validation: FAILED ($($result.Validation.Issues.Count) issues)"
                $totalFailed++
            }
        }
        
        if ($null -ne $result.Test) {
            $totalTested++
            if ($result.Test) {
                Write-Success "  Installation Test: PASSED"
            } else {
                Write-Failure "  Installation Test: FAILED"
            }
        } elseif ($result.Validation -and -not $result.Validation.CanTest) {
            Write-Info "  Installation Test: Not supported"
        }
    }
    
    Write-Host "`n" -NoNewline
    Write-Host "================================================" -ForegroundColor Cyan
    Write-Host "Total Validated: " -NoNewline
    Write-Host "$($totalPassed + $totalFailed)" -ForegroundColor Cyan
    Write-Host "Passed: " -NoNewline
    Write-Host "$totalPassed" -ForegroundColor Green
    Write-Host "Failed: " -NoNewline
    Write-Host "$totalFailed" -ForegroundColor Red
    Write-Host "Tested: " -NoNewline
    Write-Host "$totalTested" -ForegroundColor Cyan
    Write-Host "================================================" -ForegroundColor Cyan
    Write-Host ""
    
    # Exit code
    if ($totalFailed -gt 0) {
        exit 1
    } else {
        exit 0
    }
}

# Run main function
Main

#endregion
